spring:
  jpa:
    ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/mercadolivro?createDatabaseIfNotExist=true
    username: mercado
    password: Mercado@123
  jackson:
    default-property-inclusion: non_null

jwt:
  secret: Jm1TMxekOOseaCNWCQC37WePfMMkVN7SKxiVcYPvb8O2CvA78Tp9EdlbhXQTfcZ9Ii3OexTx5Bd9qNHSJUhv10
  expiration: 999999



